// One-off: self-host the Google Fonts used by the game so the app works fully
// offline. Fetches the css2 stylesheet with a modern-browser UA (to get woff2),
// downloads the latin/latin-ext subset files into fonts/, and writes
// fonts/fonts.css with local url() references.
//
//   node scripts/fetch-fonts.mjs
//
// Safe to re-run. Not part of the app; just a build helper.

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(ROOT, 'fonts');

// The exact families/weights the game uses (mirrors the old <link> in index.html).
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&family=Hanken+Grotesk:wght@400;500;600;700&family=Kalam:wght@300;400;700&display=swap';
// Chrome UA → Google serves woff2 (the smallest, best-supported format).
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
// Keep only Latin subsets — the game is English-only; drops cyrillic/vietnamese.
const KEEP = ['/* latin */', '/* latin-ext */'];

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Split into per-subset @font-face blocks (each preceded by a /* subset */ comment).
const blocks = css.split(/(?=\/\* [a-z-]+ \*\/)/).filter(b => b.includes('@font-face'));
await mkdir(FONT_DIR, { recursive: true });

let out = '/* Self-hosted fonts (generated by scripts/fetch-fonts.mjs) — offline-safe. */\n';
let n = 0;
for (const block of blocks) {
    const subset = (block.match(/\/\* ([a-z-]+) \*\//) || [])[0] || '';
    if (!KEEP.includes(subset)) continue;
    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1].trim();
    const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!family || !url) continue;
    const slug = family.toLowerCase().replace(/\s+/g, '-');
    const file = `${slug}-${weight.replace(/\s+/g, '_')}-${n}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(path.join(FONT_DIR, file), buf);
    const uni = (block.match(/unicode-range:[^;]+;/) || [''])[0];
    out += `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url(./${file}) format('woff2');\n  ${uni}\n}\n`;
    n++;
    console.log(`  ${family} ${weight} ${subset.replace(/\/\*|\*\//g, '').trim()} → fonts/${file} (${(buf.length / 1024) | 0} KB)`);
}
await writeFile(path.join(FONT_DIR, 'fonts.css'), out);
console.log(`\nWrote fonts/fonts.css with ${n} faces.`);
